import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";

const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN_X = 54;
const TOP_Y = 742;
const BOTTOM_Y = 54;
const LINE_HEIGHT = 14;
const BODY_FONT_SIZE = 10;
const TITLE_FONT_SIZE = 16;
const FOOTER_FONT_SIZE = 8;
const MAX_LINE_WIDTH = PAGE_WIDTH - MARGIN_X * 2;

export type TextPdfOptions = {
  title: string;
  body: string;
  author?: string;
  subject?: string;
  keywords?: string[];
};

function normalizeText(value: string) {
  return value
    .normalize("NFKC")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, " ");
}

function toWinAnsiSafe(value: string) {
  // pdf-lib's StandardFonts use WinAnsi encoding. This keeps PDF generation
  // deterministic until a custom embedded Unicode font is added.
  return value.replace(/[^\u0009\u000A\u000D\u0020-\u007E\u00A0-\u00FF]/g, "□");
}

function splitOversizedWord(word: string, font: PDFFont, fontSize: number, maxWidth: number) {
  const chunks: string[] = [];
  let current = "";

  for (const char of word) {
    const candidate = `${current}${char}`;
    if (current && font.widthOfTextAtSize(candidate, fontSize) > maxWidth) {
      chunks.push(current);
      current = char;
    } else {
      current = candidate;
    }
  }

  if (current) chunks.push(current);
  return chunks;
}

function wrapLine(line: string, font: PDFFont, fontSize: number, maxWidth: number) {
  const safeLine = toWinAnsiSafe(line.replace(/\t/g, "  ").trimEnd());
  if (!safeLine) return [""];

  const words = safeLine.split(/\s+/);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const wordChunks = font.widthOfTextAtSize(word, fontSize) > maxWidth
      ? splitOversizedWord(word, font, fontSize, maxWidth)
      : [word];

    for (const chunk of wordChunks) {
      const candidate = current ? `${current} ${chunk}` : chunk;
      if (!current || font.widthOfTextAtSize(candidate, fontSize) <= maxWidth) {
        current = candidate;
      } else {
        lines.push(current);
        current = chunk;
      }
    }
  }

  if (current) lines.push(current);
  return lines;
}

function drawHeader(page: PDFPage, title: string, font: PDFFont) {
  page.drawText(toWinAnsiSafe(title), {
    x: MARGIN_X,
    y: TOP_Y,
    size: TITLE_FONT_SIZE,
    font,
    color: rgb(0.08, 0.12, 0.2)
  });
}

function drawFooter(page: PDFPage, pageNumber: number, totalPages: number, font: PDFFont) {
  page.drawText(`Generated by HomeBase MLS | Page ${pageNumber} of ${totalPages}`, {
    x: MARGIN_X,
    y: 32,
    size: FOOTER_FONT_SIZE,
    font,
    color: rgb(0.37, 0.42, 0.5)
  });
}

export async function createTextPdfBuffer({ title, body, author = "HomeBase MLS", subject, keywords = [] }: TextPdfOptions) {
  const pdf = await PDFDocument.create();
  pdf.setTitle(toWinAnsiSafe(title));
  pdf.setAuthor(author);
  if (subject) pdf.setSubject(toWinAnsiSafe(subject));
  if (keywords.length > 0) pdf.setKeywords(keywords.map(toWinAnsiSafe));
  pdf.setCreator("HomeBase MLS");
  pdf.setProducer("HomeBase MLS using pdf-lib");
  pdf.setCreationDate(new Date());
  pdf.setModificationDate(new Date());

  const titleFont = await pdf.embedFont(StandardFonts.HelveticaBold);
  const bodyFont = await pdf.embedFont(StandardFonts.Helvetica);

  const normalizedLines = normalizeText(body)
    .split("\n")
    .flatMap((line) => wrapLine(line, bodyFont, BODY_FONT_SIZE, MAX_LINE_WIDTH));

  const linesPerPage = Math.max(1, Math.floor((TOP_Y - 34 - BOTTOM_Y) / LINE_HEIGHT));
  const pages: string[][] = [];

  for (let index = 0; index < normalizedLines.length; index += linesPerPage) {
    pages.push(normalizedLines.slice(index, index + linesPerPage));
  }

  if (pages.length === 0) pages.push([""]);

  pages.forEach((pageLines, index) => {
    const page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    drawHeader(page, title, titleFont);

    let y = TOP_Y - 34;
    for (const line of pageLines) {
      if (line) {
        page.drawText(line, {
          x: MARGIN_X,
          y,
          size: BODY_FONT_SIZE,
          font: bodyFont,
          color: rgb(0.12, 0.16, 0.23)
        });
      }
      y -= LINE_HEIGHT;
    }

    drawFooter(page, index + 1, pages.length, bodyFont);
  });

  const bytes = await pdf.save({ useObjectStreams: false });
  return Buffer.from(bytes);
}
