const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN_X = 54;
const TOP_Y = 742;
const BOTTOM_Y = 54;
const LINE_HEIGHT = 14;
const BODY_FONT_SIZE = 10;
const TITLE_FONT_SIZE = 16;
const MAX_CHARS_PER_LINE = 88;

function escapePdfText(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)").replace(/[\u0000-\u001F\u007F]/g, " ");
}

function wrapLine(line: string, maxChars = MAX_CHARS_PER_LINE) {
  const normalized = line.replace(/\t/g, "  ").trimEnd();
  if (normalized.length <= maxChars) return [normalized];

  const words = normalized.split(/\s+/);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    if (!current) {
      current = word;
      continue;
    }

    if (`${current} ${word}`.length <= maxChars) {
      current = `${current} ${word}`;
    } else {
      lines.push(current);
      current = word;
    }
  }

  if (current) lines.push(current);
  return lines.flatMap((wrapped) => {
    if (wrapped.length <= maxChars) return [wrapped];
    const chunks: string[] = [];
    for (let index = 0; index < wrapped.length; index += maxChars) chunks.push(wrapped.slice(index, index + maxChars));
    return chunks;
  });
}

function normalizeTextForPdf(text: string) {
  return text
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .split("\n")
    .flatMap((line) => (line.trim().length === 0 ? [""] : wrapLine(line)));
}

function pageContent(title: string, lines: string[], pageNumber: number, totalPages: number) {
  const commands: string[] = [];
  commands.push("BT");
  commands.push(`/F1 ${TITLE_FONT_SIZE} Tf`);
  commands.push(`${MARGIN_X} ${TOP_Y} Td`);
  commands.push(`(${escapePdfText(title)}) Tj`);
  commands.push("ET");

  let y = TOP_Y - 34;
  for (const line of lines) {
    commands.push("BT");
    commands.push(`/F1 ${BODY_FONT_SIZE} Tf`);
    commands.push(`${MARGIN_X} ${y} Td`);
    commands.push(`(${escapePdfText(line)}) Tj`);
    commands.push("ET");
    y -= LINE_HEIGHT;
  }

  commands.push("BT");
  commands.push("/F1 8 Tf");
  commands.push(`${MARGIN_X} 32 Td`);
  commands.push(`(Generated by HomeBase MLS | Page ${pageNumber} of ${totalPages}) Tj`);
  commands.push("ET");

  return commands.join("\n");
}

export function createTextPdfBuffer({ title, body }: { title: string; body: string }) {
  const normalizedLines = normalizeTextForPdf(body);
  const linesPerPage = Math.floor((TOP_Y - 34 - BOTTOM_Y) / LINE_HEIGHT);
  const pages: string[][] = [];

  for (let index = 0; index < normalizedLines.length; index += linesPerPage) {
    pages.push(normalizedLines.slice(index, index + linesPerPage));
  }

  if (pages.length === 0) pages.push([""]);

  const objects: string[] = [];
  const catalogId = 1;
  const pagesId = 2;
  const fontId = 3;
  const firstPageId = 4;
  const pageObjectIds = pages.map((_, index) => firstPageId + index * 2);
  const contentObjectIds = pages.map((_, index) => firstPageId + index * 2 + 1);

  objects[catalogId] = `<< /Type /Catalog /Pages ${pagesId} 0 R >>`;
  objects[pagesId] = `<< /Type /Pages /Kids [${pageObjectIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pages.length} >>`;
  objects[fontId] = `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`;

  pages.forEach((pageLines, index) => {
    const pageId = pageObjectIds[index];
    const contentId = contentObjectIds[index];
    const content = pageContent(title, pageLines, index + 1, pages.length);
    objects[pageId] = `<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`;
    objects[contentId] = `<< /Length ${Buffer.byteLength(content, "utf8")} >>\nstream\n${content}\nendstream`;
  });

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  for (let id = 1; id < objects.length; id += 1) {
    offsets[id] = Buffer.byteLength(pdf, "utf8");
    pdf += `${id} 0 obj\n${objects[id]}\nendobj\n`;
  }

  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length}\n`;
  pdf += "0000000000 65535 f \n";
  for (let id = 1; id < objects.length; id += 1) {
    pdf += `${String(offsets[id]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length} /Root ${catalogId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, "utf8");
}
