-- Updates 9-12: applicant screening, maintenance inventory, insurance/compliance, and integrations hub.
CREATE TYPE "ScreeningRequestStatus" AS ENUM ('DRAFT','ORDERED','IN_PROGRESS','NEEDS_REVIEW','APPROVED','DENIED','CANCELLED','EXPIRED');
CREATE TYPE "ScreeningCheckType" AS ENUM ('BACKGROUND','CREDIT','EVICTION','INCOME','RENTAL_HISTORY','REFERENCES','IDENTITY');
CREATE TYPE "VerificationStatus" AS ENUM ('NOT_STARTED','REQUESTED','IN_REVIEW','VERIFIED','FAILED','WAIVED');
CREATE TYPE "MaintenanceAssetType" AS ENUM ('APPLIANCE','HVAC','WATER_HEATER','ELECTRICAL','PLUMBING','KEY','LOCK','ROOF','SECURITY','OTHER');
CREATE TYPE "MaintenanceAssetStatus" AS ENUM ('ACTIVE','NEEDS_SERVICE','RETIRED','LOST','REPLACED');
CREATE TYPE "ComplianceRecordStatus" AS ENUM ('CURRENT','EXPIRING_SOON','EXPIRED','MISSING','WAIVED');
CREATE TYPE "InsurancePolicyType" AS ENUM ('RENTERS','LANDLORD','LIABILITY','FLOOD','UMBRELLA','OTHER');
CREATE TYPE "IntegrationProvider" AS ENUM ('STRIPE','PLAID','TWILIO','SENDGRID','POSTMARK','S3','R2','QUICKBOOKS','GOOGLE_CALENDAR','GOOGLE_MAPS','SCREENING_PROVIDER','OTHER');
CREATE TYPE "IntegrationConnectionStatus" AS ENUM ('NOT_CONFIGURED','CONFIGURED','CONNECTED','ERROR','DISABLED');
CREATE TYPE "IntegrationEventStatus" AS ENUM ('QUEUED','SUCCESS','FAILED','SKIPPED');

CREATE TABLE "ScreeningPackage" ("id" TEXT PRIMARY KEY, "ownerId" TEXT, "name" TEXT NOT NULL, "description" TEXT, "priceCents" INTEGER, "includesBackground" BOOLEAN NOT NULL DEFAULT true, "includesCredit" BOOLEAN NOT NULL DEFAULT false, "includesEviction" BOOLEAN NOT NULL DEFAULT true, "includesIncome" BOOLEAN NOT NULL DEFAULT true, "includesRentalHistory" BOOLEAN NOT NULL DEFAULT true, "includesReferences" BOOLEAN NOT NULL DEFAULT true, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "ApplicantScreening" ("id" TEXT PRIMARY KEY, "applicationId" TEXT NOT NULL, "unitId" TEXT, "packageId" TEXT, "providerName" TEXT, "providerOrderId" TEXT, "status" "ScreeningRequestStatus" NOT NULL DEFAULT 'DRAFT', "recommendation" TEXT, "riskSummary" TEXT, "orderedById" TEXT, "reviewedById" TEXT, "orderedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "reviewedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "IncomeVerification" ("id" TEXT PRIMARY KEY, "applicationId" TEXT NOT NULL, "screeningId" TEXT, "employerName" TEXT, "monthlyIncomeCents" INTEGER, "status" "VerificationStatus" NOT NULL DEFAULT 'NOT_STARTED', "source" TEXT, "notes" TEXT, "verifiedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "RentalHistoryVerification" ("id" TEXT PRIMARY KEY, "applicationId" TEXT NOT NULL, "screeningId" TEXT, "landlordName" TEXT, "landlordEmail" TEXT, "landlordPhone" TEXT, "address" TEXT, "status" "VerificationStatus" NOT NULL DEFAULT 'NOT_STARTED', "notes" TEXT, "verifiedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "ScreeningReference" ("id" TEXT PRIMARY KEY, "applicationId" TEXT NOT NULL, "screeningId" TEXT, "name" TEXT NOT NULL, "email" TEXT, "phone" TEXT, "relationship" TEXT, "status" "VerificationStatus" NOT NULL DEFAULT 'NOT_STARTED', "notes" TEXT, "contactedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "BackgroundCheckRequest" ("id" TEXT PRIMARY KEY, "applicationId" TEXT NOT NULL, "screeningId" TEXT, "checkType" "ScreeningCheckType" NOT NULL DEFAULT 'BACKGROUND', "providerName" TEXT, "providerReference" TEXT, "status" "VerificationStatus" NOT NULL DEFAULT 'NOT_STARTED', "summary" TEXT, "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "MaintenanceAsset" ("id" TEXT PRIMARY KEY, "ownerId" TEXT, "propertyId" TEXT, "unitId" TEXT, "type" "MaintenanceAssetType" NOT NULL, "status" "MaintenanceAssetStatus" NOT NULL DEFAULT 'ACTIVE', "name" TEXT NOT NULL, "make" TEXT, "model" TEXT, "serialNumber" TEXT, "location" TEXT, "installedAt" TIMESTAMP(3), "warrantyExpiresAt" TIMESTAMP(3), "nextServiceDueAt" TIMESTAMP(3), "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "AssetServiceRecord" ("id" TEXT PRIMARY KEY, "assetId" TEXT NOT NULL, "maintenanceRequestId" TEXT, "createdById" TEXT, "serviceDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "vendorName" TEXT, "summary" TEXT NOT NULL, "costCents" INTEGER, "nextServiceDueAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "AssetWarranty" ("id" TEXT PRIMARY KEY, "assetId" TEXT NOT NULL, "providerName" TEXT, "policyNumber" TEXT, "coverageNotes" TEXT, "expiresAt" TIMESTAMP(3), "documentUrl" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "KeyLockRecord" ("id" TEXT PRIMARY KEY, "assetId" TEXT NOT NULL, "keyCode" TEXT, "lockLocation" TEXT, "issuedTo" TEXT, "issuedAt" TIMESTAMP(3), "returnedAt" TIMESTAMP(3), "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "InsurancePolicy" ("id" TEXT PRIMARY KEY, "ownerId" TEXT, "propertyId" TEXT, "unitId" TEXT, "applicationId" TEXT, "type" "InsurancePolicyType" NOT NULL, "status" "ComplianceRecordStatus" NOT NULL DEFAULT 'MISSING', "providerName" TEXT, "policyNumber" TEXT, "coverageAmountCents" INTEGER, "effectiveAt" TIMESTAMP(3), "expiresAt" TIMESTAMP(3), "documentUrl" TEXT, "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "CertificationRecord" ("id" TEXT PRIMARY KEY, "ownerId" TEXT, "propertyId" TEXT, "unitId" TEXT, "name" TEXT NOT NULL, "status" "ComplianceRecordStatus" NOT NULL DEFAULT 'MISSING', "issuingAuthority" TEXT, "certificateNumber" TEXT, "issuedAt" TIMESTAMP(3), "expiresAt" TIMESTAMP(3), "documentUrl" TEXT, "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "ComplianceInspectionRequirement" ("id" TEXT PRIMARY KEY, "propertyId" TEXT, "unitId" TEXT, "name" TEXT NOT NULL, "status" "ComplianceRecordStatus" NOT NULL DEFAULT 'MISSING', "requiredEveryMonths" INTEGER, "lastCompletedAt" TIMESTAMP(3), "nextDueAt" TIMESTAMP(3), "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "IntegrationConnection" ("id" TEXT PRIMARY KEY, "ownerId" TEXT, "provider" "IntegrationProvider" NOT NULL, "status" "IntegrationConnectionStatus" NOT NULL DEFAULT 'NOT_CONFIGURED', "displayName" TEXT NOT NULL, "accountReference" TEXT, "configJson" JSONB, "lastSyncAt" TIMESTAMP(3), "lastError" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "IntegrationEvent" ("id" TEXT PRIMARY KEY, "connectionId" TEXT, "actorId" TEXT, "provider" "IntegrationProvider" NOT NULL, "status" "IntegrationEventStatus" NOT NULL DEFAULT 'QUEUED', "eventType" TEXT NOT NULL, "summary" TEXT, "payloadJson" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);

ALTER TABLE "ScreeningPackage" ADD CONSTRAINT "ScreeningPackage_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ApplicantScreening" ADD CONSTRAINT "ApplicantScreening_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ApplicantScreening" ADD CONSTRAINT "ApplicantScreening_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ApplicantScreening" ADD CONSTRAINT "ApplicantScreening_packageId_fkey" FOREIGN KEY ("packageId") REFERENCES "ScreeningPackage"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ApplicantScreening" ADD CONSTRAINT "ApplicantScreening_orderedById_fkey" FOREIGN KEY ("orderedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ApplicantScreening" ADD CONSTRAINT "ApplicantScreening_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "IncomeVerification" ADD CONSTRAINT "IncomeVerification_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "IncomeVerification" ADD CONSTRAINT "IncomeVerification_screeningId_fkey" FOREIGN KEY ("screeningId") REFERENCES "ApplicantScreening"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RentalHistoryVerification" ADD CONSTRAINT "RentalHistoryVerification_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RentalHistoryVerification" ADD CONSTRAINT "RentalHistoryVerification_screeningId_fkey" FOREIGN KEY ("screeningId") REFERENCES "ApplicantScreening"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ScreeningReference" ADD CONSTRAINT "ScreeningReference_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ScreeningReference" ADD CONSTRAINT "ScreeningReference_screeningId_fkey" FOREIGN KEY ("screeningId") REFERENCES "ApplicantScreening"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "BackgroundCheckRequest" ADD CONSTRAINT "BackgroundCheckRequest_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BackgroundCheckRequest" ADD CONSTRAINT "BackgroundCheckRequest_screeningId_fkey" FOREIGN KEY ("screeningId") REFERENCES "ApplicantScreening"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MaintenanceAsset" ADD CONSTRAINT "MaintenanceAsset_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MaintenanceAsset" ADD CONSTRAINT "MaintenanceAsset_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MaintenanceAsset" ADD CONSTRAINT "MaintenanceAsset_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AssetServiceRecord" ADD CONSTRAINT "AssetServiceRecord_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "MaintenanceAsset"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AssetServiceRecord" ADD CONSTRAINT "AssetServiceRecord_maintenanceRequestId_fkey" FOREIGN KEY ("maintenanceRequestId") REFERENCES "MaintenanceRequest"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AssetServiceRecord" ADD CONSTRAINT "AssetServiceRecord_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AssetWarranty" ADD CONSTRAINT "AssetWarranty_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "MaintenanceAsset"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "KeyLockRecord" ADD CONSTRAINT "KeyLockRecord_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "MaintenanceAsset"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "InsurancePolicy" ADD CONSTRAINT "InsurancePolicy_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "InsurancePolicy" ADD CONSTRAINT "InsurancePolicy_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "InsurancePolicy" ADD CONSTRAINT "InsurancePolicy_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "InsurancePolicy" ADD CONSTRAINT "InsurancePolicy_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CertificationRecord" ADD CONSTRAINT "CertificationRecord_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CertificationRecord" ADD CONSTRAINT "CertificationRecord_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CertificationRecord" ADD CONSTRAINT "CertificationRecord_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ComplianceInspectionRequirement" ADD CONSTRAINT "ComplianceInspectionRequirement_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ComplianceInspectionRequirement" ADD CONSTRAINT "ComplianceInspectionRequirement_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "IntegrationConnection" ADD CONSTRAINT "IntegrationConnection_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "IntegrationEvent" ADD CONSTRAINT "IntegrationEvent_connectionId_fkey" FOREIGN KEY ("connectionId") REFERENCES "IntegrationConnection"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "IntegrationEvent" ADD CONSTRAINT "IntegrationEvent_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE UNIQUE INDEX "IntegrationConnection_ownerId_provider_displayName_key" ON "IntegrationConnection"("ownerId","provider","displayName");
CREATE INDEX "ScreeningPackage_ownerId_isActive_idx" ON "ScreeningPackage"("ownerId","isActive");
CREATE INDEX "ApplicantScreening_applicationId_idx" ON "ApplicantScreening"("applicationId");
CREATE INDEX "ApplicantScreening_unitId_idx" ON "ApplicantScreening"("unitId");
CREATE INDEX "ApplicantScreening_status_idx" ON "ApplicantScreening"("status");
CREATE INDEX "ApplicantScreening_orderedAt_idx" ON "ApplicantScreening"("orderedAt");
CREATE INDEX "MaintenanceAsset_ownerId_idx" ON "MaintenanceAsset"("ownerId");
CREATE INDEX "MaintenanceAsset_propertyId_idx" ON "MaintenanceAsset"("propertyId");
CREATE INDEX "MaintenanceAsset_unitId_idx" ON "MaintenanceAsset"("unitId");
CREATE INDEX "MaintenanceAsset_type_idx" ON "MaintenanceAsset"("type");
CREATE INDEX "MaintenanceAsset_status_idx" ON "MaintenanceAsset"("status");
CREATE INDEX "MaintenanceAsset_nextServiceDueAt_idx" ON "MaintenanceAsset"("nextServiceDueAt");
CREATE INDEX "InsurancePolicy_ownerId_idx" ON "InsurancePolicy"("ownerId");
CREATE INDEX "InsurancePolicy_status_idx" ON "InsurancePolicy"("status");
CREATE INDEX "InsurancePolicy_expiresAt_idx" ON "InsurancePolicy"("expiresAt");
CREATE INDEX "CertificationRecord_ownerId_idx" ON "CertificationRecord"("ownerId");
CREATE INDEX "CertificationRecord_status_idx" ON "CertificationRecord"("status");
CREATE INDEX "CertificationRecord_expiresAt_idx" ON "CertificationRecord"("expiresAt");
CREATE INDEX "ComplianceInspectionRequirement_status_idx" ON "ComplianceInspectionRequirement"("status");
CREATE INDEX "ComplianceInspectionRequirement_nextDueAt_idx" ON "ComplianceInspectionRequirement"("nextDueAt");
CREATE INDEX "IntegrationConnection_ownerId_idx" ON "IntegrationConnection"("ownerId");
CREATE INDEX "IntegrationConnection_provider_idx" ON "IntegrationConnection"("provider");
CREATE INDEX "IntegrationConnection_status_idx" ON "IntegrationConnection"("status");
CREATE INDEX "IntegrationEvent_connectionId_idx" ON "IntegrationEvent"("connectionId");
CREATE INDEX "IntegrationEvent_actorId_idx" ON "IntegrationEvent"("actorId");
CREATE INDEX "IntegrationEvent_provider_idx" ON "IntegrationEvent"("provider");
CREATE INDEX "IntegrationEvent_status_idx" ON "IntegrationEvent"("status");
CREATE INDEX "IntegrationEvent_createdAt_idx" ON "IntegrationEvent"("createdAt");
